///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace GitTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GitTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("edb3c178-a9d1-4317-8118-d8eac76ed077")]
    public partial class GitTestRepository : RepoGenBaseFolder
    {
        static GitTestRepository instance = new GitTestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the GitTestRepository element repository.
        /// </summary>
        [RepositoryFolder("edb3c178-a9d1-4317-8118-d8eac76ed077")]
        public static GitTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GitTestRepository() 
            : base("GitTestRepository", "/", null, 0, false, "edb3c178-a9d1-4317-8118-d8eac76ed077", ".\\RepositoryImages\\GitTestRepositoryedb3c178.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("edb3c178-a9d1-4317-8118-d8eac76ed077")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class GitTestRepositoryFolders
    {
    }
#pragma warning restore 0436
}